### ISSUE TITLE
HRSC to DOTA

### ISSUE THREAD

**Issue by molimoli233** [ming71/toolbox#12]
不好意思打扰了，我是一名小白，水平太弱了，能烦请作者将HRSC转DOTA的时，存放HRSC数据集文件目录结构告知一下么，文件路径总是错，万分感谢

**Comment by ming71** [comment]
不好意思现在才注意到你的问题。
HRSC目录直接按照原结构解压就行，converter代码里面会处理的，如果还有问题可以邮箱联系。
