### ISSUE TITLE
One xml that has two or more same objects can not convert to coco json which has same bbox

### ISSUE THREAD

**Issue by LIUhansen** [ming71/toolbox#3]

**Comment by ming71** [comment]
What does the `same objects` mean?  One groundtruth ought to be labeled once . I don't figure out what' your meaning ==

**Comment by LIUhansen** [comment]
One category has two or more objects in the same image,

**Comment by ming71** [comment]
ummm, sorry for your inconvenience usage.
I didn't spent time figuring out COCO's json format before, thus the `voc2coco.py` is not coded by myself, I just debug with the code and can not work with your problem.
But if you attempt to convert VOC labels to COCO format for **object detection**, there is **no need** to generate json file.

**Comment by LIUhansen** [comment]
That's all right. I have solved that problem,and perhaps that mistake caused by changing your code.Thanks for your attention.
