### ISSUE TITLE
index 5 is out of bounds for axis 1 with size 5

### ISSUE THREAD

**Issue by surajbharadwaj** [ming71/toolbox#4]
what is the format of your label file? is it yolo text file?

eg:  0 0.717448 0.654630 0.168229 0.244444

but what is boxes_a = labels[:,5] in class  Copy paste?
there is no fifth element in text file. or which format are you using?

**Comment by ming71** [comment]
which file did you refer to?
There 3 txt formats in this repo :
* NWPU
* yolo
* yolo(r)
maybe you ref→ `yolo(r)` In this case, the fifth  element is theta uesd to encode rotation info(range from -0.5*pi to 0.5pi )
