### ISSUE TITLE
border value in Affine

### ISSUE THREAD

**Issue by junliang230** [ming71/toolbox#5]
could I ask you a question about [bordervalue](https://github.com/ming71/toolbox/blob/master/data_augmentation/augmentation.py#L33) why not this value is set to imageNet mean value like [123.675, 116.28, 103.53]
thanks your reply

**Comment by ming71** [comment]
yeah, cause the value is just used to fill the part without any content, it doesn't matter. Further, you can set it to any possible value (such as [0,0,0] or [255,255,255]) that will not cause ambiguity, that is to say , your conv-net won't mistake these border regions as ground truths.

**Comment by junliang230** [comment]
thanks your reply
