### ISSUE TITLE
A litter error, u can fix it

### ISSUE THREAD

**Issue by eguoguo321** [ming71/toolbox#6]
voc2coco.py
line 288:
```
PascalVOC2coco(xml_file, 'train.json')

```

should be 
```
PascalVOC2coco(xml_files, 'train.json')

```

**Comment by eguoguo321** [comment]
U did a good job,ZAN!

**Comment by ming71** [comment]
Thanks. Some of the format conversion codes have been deprecated. I will update these files when I'm free.
