### ISSUE TITLE
HRSC2016转COCO格式 不包含角度信息

### ISSUE THREAD

**Issue by kongyan66** [ming71/toolbox#8]
作者您好,再次打扰了！关于你的https://github.com/kongyan66/toolbox/blob/master/converter/toCOCO/HRSC2COCO.py
这个脚本测试成功，但我发现生成.json文件不包含角度信息，不适配旋转检测器训练，我尝试加入角度信息，效果不太好，
请问作者怎么解决的呢？谢谢

**Comment by ming71** [comment]
我转的都是dota格式的polygon。如果你的检测器要角度信息，在dataload部分自己处理一下quad转成obb就行。

**Comment by kongyan66** [comment]
嗯好，我尝试下，谢谢答复
