### ISSUE TITLE
ModuleNotFoundError: No module named 'dota_utils'

### ISSUE THREAD

**Issue by happy20200** [ming71/toolbox#9]
ModuleNotFoundError: No module named 'dota_utils'

**Comment by ming71** [comment]
`dota_utils` is included [here](https://github.com/ming71/toolbox/blob/master/dataset/DOTA_devkit/dota_utils.py) . 
Please check your path carefully.

**Comment by Luian0297** [comment]
> ModuleNotFoundError: No module named 'dota_utils'

Can I ask you a few questions?
